#!/usr/bin/env python3
"""Publish each catalogued tool's logo into its GitHub repository.

The site renders logos from ``images/tools/<key>.svg`` (generated by
_generators/gen_tool_logos.py).  This helper mirrors the same file to the root
of ``labxscut/<tool>`` as ``logo.svg`` through the GitHub Contents API, so every
tool repository carries its own logo next to its README.

Only tools whose ``repo`` points at github.com/labxscut are published, and a
repository that already has a hand-made ``logo.svg`` is left untouched unless
``--force`` is given.

Usage:  gh auth login   # once
        python scripts/publish_tool_logos.py [--dry-run] [--force] [--message TEXT]
"""
from __future__ import annotations

import argparse
import base64
import json
import subprocess
import sys
from pathlib import Path

import yaml

SITE_ROOT = Path(__file__).resolve().parents[1]
TOOLS_DATA = SITE_ROOT / "_data" / "tools.yml"
LOGO_DIR = SITE_ROOT / "images" / "tools"
REPO_TARGET = "logo.svg"
ORG_PREFIX = "https://github.com/labxscut/"


class PublishError(RuntimeError):
    """Raised when the GitHub API call fails."""


def gh(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(
        ["gh", *args],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if check and result.returncode:
        detail = (result.stderr or result.stdout).strip()
        raise PublishError(f"gh {' '.join(args)} failed: {detail}")
    return result


def repository_name(url: str) -> str | None:
    if not url or not url.startswith(ORG_PREFIX):
        return None
    name = url[len(ORG_PREFIX) :].strip("/")
    if "/" in name:
        return None
    return name


def default_branch(repository: str) -> str:
    return gh("api", f"repos/labxscut/{repository}", "--jq", ".default_branch").stdout.strip()


def current_sha(repository: str) -> str | None:
    result = gh("api", f"repos/labxscut/{repository}/contents/{REPO_TARGET}", check=False)
    if result.returncode:
        return None
    try:
        return json.loads(result.stdout).get("sha")
    except json.JSONDecodeError:
        return None


def put_logo(
    repository: str, content: bytes, message: str, sha: str | None, branch: str
) -> str:
    payload = {
        "message": message,
        "content": base64.b64encode(content).decode("ascii"),
        "branch": branch,
    }
    if sha:
        payload["sha"] = sha
    result = subprocess.run(
        [
            "gh",
            "api",
            f"repos/labxscut/{repository}/contents/{REPO_TARGET}",
            "--method",
            "PUT",
            "--input",
            "-",
        ],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        input=json.dumps(payload),
    )
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()
        raise PublishError(f"upload to {repository} failed: {detail}")
    try:
        commit = json.loads(result.stdout)["commit"]["sha"]
    except (KeyError, json.JSONDecodeError) as error:
        raise PublishError(f"unexpected response for {repository}: {error}") from error
    return commit[:12]


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true", help="replace existing logo.svg")
    parser.add_argument(
        "--message",
        default=f"Add LabX tool logo\n\nCo-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>",
    )
    args = parser.parse_args(argv)

    tools = yaml.safe_load(TOOLS_DATA.read_text(encoding="utf-8"))
    published = skipped = missing = 0
    for tool in tools:
        key = tool["key"]
        repository = repository_name(tool.get("repo", ""))
        if not repository:
            print(f"{key}: no labxscut repository, skipped")
            skipped += 1
            continue
        logo = LOGO_DIR / f"{key}.svg"
        if not logo.is_file():
            print(f"{key}: {logo} is missing, run _generators/gen_tool_logos.py first")
            missing += 1
            continue
        content = logo.read_bytes()
        branch = default_branch(repository)
        sha = current_sha(repository)
        if sha and not args.force:
            print(f"{repository}: {REPO_TARGET} already exists, use --force to replace")
            skipped += 1
            continue
        if args.dry_run:
            print(f"{repository}: would {'replace' if sha else 'add'} {REPO_TARGET} on {branch}")
            published += 1
            continue
        commit = put_logo(repository, content, args.message, sha, branch)
        print(f"{repository}: {REPO_TARGET} -> {commit} ({branch})")
        published += 1

    print(f"published: {published}, skipped: {skipped}, missing logos: {missing}")
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
