#!/usr/bin/env python3
"""Build the people data (_data/people.yml) and per-member pages (/team/<nick>/index.md)
from the roster source of truth.

Source of truth: ~/work/advisee/core/database/contact.md (roster SoT).
Only public-safe fields are copied to the website: nick, English/Chinese name,
degree, entry/exit year, status, generic affiliation, GitHub handle, and links
to their tools/papers.  Contact details (email, mobile, WeChat/WeCom ids,
leader assignments, free-text notes) are deliberately NOT published.

Rule for individual pages: current group members get a page at /team/<nick>/
only when verified CV, publication, teaching, or tool material is available.
Alumni and external collaborators are listed on /team/ only.

Usage (WSL):  python3 _generators/gen_people.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from urllib.parse import urlsplit

import yaml

try:  # optional: only needed to recognise Chinese-order names
    from pypinyin import lazy_pinyin
except ImportError:  # pragma: no cover
    lazy_pinyin = None

from gen_avatars import AVATAR_ROOT, ensure_avatar
from gen_publications import REPO, load_roster

OUT_DIR = REPO
TEAM_DIR = "team"
PROFILE_ROOT = REPO / TEAM_DIR
LEGACY_OUT_DIR = REPO / "_people"
DATA = REPO / "_data"
PUBLICATIONS = DATA / "publications.yml"
TOOLS = DATA / "tools.yml"
MEMBER_PROFILES = DATA / "member_profiles.yml"
PAGE_MARKER = "<!-- Generated by _generators/gen_people.py; edit the roster source instead. -->"

# Roster ``Type=`` markers that describe a relationship outside the membership.
TYPE_SECTIONS = {
    "Collaborator": "collaborator",
    "VisitingScholar": "visiting",
}

# Rows whose relationship to the lab is decided by the roster markers rather than
# their degree cell. Kept empty so ``Type=`` / ``Alumni=`` markers are authoritative.
EXTERNAL_FACULTY: set[str] = set()

DEGREE_ROLE = {
    "Faculty": "Faculty",
    "PostDoc": "Postdoctoral researcher",
    "PhD": "PhD student",
    "Master": "Master's student",
    "Under": "Undergraduate researcher",
}

TITLE_BY_SECTION = {
    "pi": "Principal Investigator",
    "faculty": "Faculty",
    "phd": "PhD student",
    "master": "Master's student",
    "under": "Undergraduate researcher",
    "collaborator": "Collaborator",
    "visiting": "Visiting scholar",
}

# Alumni keep the level they reached in the lab rather than a current-role title.
ALUMNI_ROLE = {
    "Faculty": "Faculty",
    "PostDoc": "Postdoctoral researcher",
    "PhD": "PhD",
    "Master": "Master's",
    "Under": "Undergraduate",
}

# Alumni are grouped by the level they left at: highest first, then most recent exit.
ALUMNI_RANK = {"Faculty": 0, "PostDoc": 1, "PhD": 2, "Master": 3, "Under": 4}
# the sub-sections /team/ shows inside Alumni, in display order
ALUMNI_GROUP_ORDER = ["Visiting scholars", "Postdocs", "PhD", "Master's", "Undergraduates"]
# a visiting scholar's displayed role, unless the roster carries a more specific title
ALUMNI_VISITING_ROLE = "Visiting scholar"


ALUMNI_POSTDOC_ROLE = "Postdoctoral researcher"


def alumni_group(degree: str, now: str, title: str, type_: str) -> dict:
    """Alumni sub-section rank and role text for one alumnus.

    A roster ``type`` of ``VisitingScholar`` (or a postdoctoral position) wins over
    the study level, so visiting scholars and postdocs are listed above the
    PhD / Master's / undergraduate groups.
    """
    if type_ == "VisitingScholar":
        rank = 0
        role = role_text(title, ALUMNI_VISITING_ROLE) if title else ALUMNI_VISITING_ROLE
        fallback = ALUMNI_VISITING_ROLE
    elif now.lower().startswith("postdoc"):
        rank, role, fallback = 1, ALUMNI_POSTDOC_ROLE, ALUMNI_POSTDOC_ROLE
    else:
        rank = ALUMNI_RANK.get(degree, 4)
        role = ALUMNI_ROLE.get(degree, "Alumni")
        fallback = role
    return {"rank": rank, "label": ALUMNI_GROUP_ORDER[rank], "role": role, "fallback": fallback}

# Order of the /team/ sections; also the order people.yml is written in.
# Collaborators and visiting scholars are current collaborators, so they sit
# right after the faculty rather than trailing the alumni.
SECTION_ORDER = ["pi", "faculty", "collaborator", "visiting", "phd", "master", "under", "alumni"]

SCUT_AFFILIATION = {"", "n.a.", "在校", "华南理工大学"}

# Institute names in a note `title` that mean "here at LabX"; keeping them in the
# displayed role would only repeat the affiliation everyone already sees.
SCUT_TITLE_PLACES = {"SCUT", "华南理工大学", "South China University of Technology"}

# Affiliation cells that carry no information about where someone is now.
PLACEHOLDER_AFFILIATIONS = {"", "n.a.", "—", "-", "待定", "TBD", "华南理工大学"}

# Vague career notes rather than an institution; not published as a "now" line.
NON_INSTITUTIONAL_AFFILIATIONS = {
    "就业",
    "备考研究生",
    "待业",
    "工作",
    "出国",
}

PI_NICK = "lcx"


def section_for(row: dict) -> str:
    if row["nick"] == "lcx":
        return "pi"
    is_alumni = bool(row["status"] == "alumni" or row.get("alumni") or row["nick"] in EXTERNAL_FACULTY)
    type_section = TYPE_SECTIONS.get(row.get("type", ""))
    # a departed visiting scholar belongs to the Alumni section (shown as its own
    # sub-group); the top-level `visiting` section is for current visitors only
    if type_section and not (is_alumni and type_section == "visiting"):
        return type_section
    if is_alumni:
        return "alumni"
    return {
        "Faculty": "faculty",
        "PhD": "phd",
        "Master": "master",
        "Under": "under",
    }.get(row["degree"], "under")


def alumni_rank(entry: dict) -> tuple[int, int]:
    """Sort key for alumni: sub-group first, then most recent departure."""
    label = entry.get("alumni_group") or ""
    if label in ALUMNI_GROUP_ORDER:
        rank = ALUMNI_GROUP_ORDER.index(label)
    else:
        rank = ALUMNI_RANK.get(entry["degree"], len(ALUMNI_GROUP_ORDER) - 1)
    end = re.sub(r"\D", "", str(entry.get("end_year") or ""))
    return rank, -(int(end) if end else 0)





def years(row: dict) -> tuple[str, str]:
    """'2023i' -> ('2023', '');  '2022/2025o' -> ('2022', '2025');  '2019o' -> ('', '2019')."""
    year = (row["year"] or "").strip()
    parts = year.split("/")
    start = re.sub(r"\D", "", parts[0]) if parts and parts[0] else ""
    end = re.sub(r"\D", "", parts[1]) if len(parts) > 1 else ""
    if len(parts) == 1 and year.endswith("o"):
        return "", start
    return start, end


def short_year(year: str) -> str:
    """'2026' -> '26'; leave anything that is not a four-digit year alone."""
    return year[2:] if len(year) == 4 and year.isdigit() else year


def years_label(row: dict, start: str, end: str) -> str:
    """Render membership years unambiguously as ``YYi`` / ``YYi–YYo``.

    The century is dropped ("26i") because the lab is young enough that no two
    membership years can be confused across a century boundary.
    """
    year = (row["year"] or "").strip()
    if not year:
        return ""
    if start and end:
        return f"{short_year(start)}i–{short_year(end)}o"
    if end:
        return f"{short_year(end)}o"
    if start:
        return f"{short_year(start)}o" if year.endswith("o") else f"{short_year(start)}i"
    return year


# Chinese and English spellings of the same institution, so "浙江大学" and
# "master@Zhejiang University" are not published side by side as two places.
INSTITUTION_ALIASES = {
    "浙江大学": {"zhejiang university", "zju"},
    "中山大学": {"sun yat-sen university", "sysu"},
    "华南理工大学": {"south china university of technology", "scut"},
    "海外": {"overseas", "海外phd申请中"},
    "北京大学": {"peking university", "pku"},
    "清华大学": {"tsinghua university"},
}


def _place_key(text: str) -> str:
    return text.strip().lower().replace(" ", "")


def same_place(left: str, right: str) -> bool:
    """True when two strings name the same institution in either language."""
    a, b = _place_key(left), _place_key(right)
    if not a or not b:
        return False
    if a == b or a in b or b in a:
        return True
    for zh, en_names in INSTITUTION_ALIASES.items():
        names = {_place_key(n) for n in en_names} | {_place_key(zh)}

        def matches(text: str) -> bool:
            return text in names or any(n in text or text in n for n in names)

        if matches(a) and matches(b):
            return True
    return False


def place_text(now: str) -> str:
    """'postdoc@Stanford' -> 'postdoc@Stanford'; '@NetEase Games' -> 'NetEase Games'."""
    role, _, place = now.partition("@")
    role, place = role.strip(), place.strip()
    if role and place:
        return f"{role}@{place}"
    return role or place or now


def role_text(title: str, fallback: str) -> str:
    """'Associate Professor@SCUT' -> 'Associate Professor'.

    A title held away from SCUT keeps its institute, because the institute is
    the part of the role that tells readers where the person actually works.
    """
    if not title:
        return fallback
    role, _, place = title.partition("@")
    role, place = role.strip(), place.strip()
    if not role:
        return fallback
    if not place or place in SCUT_TITLE_PLACES:
        return role
    return f"{role}@{place}"


CJK_RE = re.compile(r"[\u4e00-\u9fff]+")


def _pinyin(text: str) -> list[str]:
    """One lowercase pinyin syllable per Chinese character; [] if not all Chinese."""
    if lazy_pinyin is None or not text:
        return []
    if not CJK_RE.fullmatch(text):
        return []
    return [s.lower() for s in lazy_pinyin(text)]


def first_last(name_en: str, name_zh: str) -> str:
    """Render a roster English name in Western `First Last` order.

    The roster keeps Chinese order (`Surname Given`, e.g. ``Duan Hongyu``); the
    site shows ``Hongyu Duan``. The Chinese cell decides: a two-token name whose
    first token spells the surname character is swapped. Names already in
    Western order (``Kaida Ning`` — first token spells the *given* characters),
    middle initials, and anything that cannot be matched are left untouched.
    Given names romanised unusually (``Deng Siyuan`` for 邓偲媛) still swap.
    """
    tokens = name_en.split()
    if len(tokens) != 2:
        return name_en
    first, second = tokens
    syl = _pinyin(name_zh)
    if len(syl) < 2:
        return name_en
    if "".join(syl[1:]) == first.lower():
        return name_en  # already `Given Surname`
    if first.lower() != syl[0]:
        return name_en
    return f"{second} {first}"


def short_paper(entry: dict) -> dict:
    return {
        "slug": entry["slug"],
        "title": entry["title"],
        "venue": entry.get("venue_short") or entry["venue"],
        "year": entry["year"],
        "url": entry["url"],
        "status": entry.get("status", ""),
        "pi_track": entry.get("pi_track", ""),
        "doi": entry.get("doi", ""),
        "published_on": entry.get("published_on", ""),
        "volume": entry.get("volume", ""),
        "issue": entry.get("issue", ""),
        "pages": entry.get("pages", ""),
        "pdf": entry.get("pdf", ""),
        "sort_key": entry.get("sort_key", entry.get("year", "")),
    }


def tracked_profile_nicks() -> set[str]:
    result = subprocess.run(
        ["git", "-C", str(REPO), "ls-tree", "-r", "--name-only", "HEAD", "--", TEAM_DIR],
        check=True,
        capture_output=True,
        text=True,
    )
    return {
        parts[1]
        for path in result.stdout.splitlines()
        if len(parts := path.split("/")) == 3
        and parts[0] == TEAM_DIR
        and parts[2] == "index.md"
    }


def cv_links_by_member(
    profiles: list[dict], roster_nicks: set[str]
) -> dict[str, str]:
    """Return verified-format public PDF links keyed by roster nick."""
    cv_by_member: dict[str, str] = {}
    for item in profiles:
        nick = item.get("nick")
        cv_url = item.get("cv_url")
        if not nick or not cv_url:
            continue
        if nick not in roster_nicks:
            raise ValueError(f"unknown member in {MEMBER_PROFILES}: {nick}")
        parsed_cv = urlsplit(cv_url)
        if parsed_cv.scheme != "https" or not parsed_cv.path.lower().endswith(".pdf"):
            raise ValueError(f"CV URL must be an HTTPS PDF link for {nick}: {cv_url}")
        repository_url = item.get("cv_repository_url", "")
        if repository_url:
            parsed_repository = urlsplit(repository_url)
            repository_name = parsed_repository.path.rstrip("/").split("/")[-1]
            if (
                parsed_repository.scheme != "https"
                or parsed_repository.netloc.lower() != "github.com"
                or repository_name.casefold() != nick.casefold()
            ):
                raise ValueError(
                    f"CV repository must be a public GitHub repository named for "
                    f"{nick}: {repository_url}"
                )
        cv_by_member[nick] = cv_url
    return cv_by_member


def write_team_redirect(path, nick: str) -> None:
    front = {
        "layout": "default",
        "permalink": f"/team/{nick}/",
        "redirect_to": "/team/",
        "redirect_from": [f"/{nick}/", f"/people/{nick}/"],
        "nick": nick,
        "has_page": False,
        "title": "Team",
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and PAGE_MARKER not in path.read_text(encoding="utf-8"):
        raise RuntimeError(f"refusing to overwrite hand-maintained profile: {path}")
    path.write_text(
        "---\n"
        + yaml.safe_dump(front, allow_unicode=True, sort_keys=False, width=100).strip()
        + f"\n---\n\n{PAGE_MARKER}\n",
        encoding="utf-8",
    )


def main() -> int:
    previous_profiles = tracked_profile_nicks()
    roster = load_roster()
    pub_docs: list[dict] = []
    if PUBLICATIONS.exists():
        pub_docs = yaml.safe_load(PUBLICATIONS.read_text(encoding="utf-8")) or []
    tool_docs = yaml.safe_load(TOOLS.read_text(encoding="utf-8")) or []
    teaching_docs = yaml.safe_load(
        (DATA / "member_teaching.yml").read_text(encoding="utf-8")
    ) or []
    member_profile_docs = yaml.safe_load(
        MEMBER_PROFILES.read_text(encoding="utf-8")
    ) or []
    cv_by_member = cv_links_by_member(
        member_profile_docs, {row["nick"] for row in roster}
    )
    tools_by_member: dict[str, set[str]] = {}
    for tool in tool_docs:
        for nick in tool.get("maintainers") or []:
            tools_by_member.setdefault(nick, set()).add(tool["key"])
    teaching_by_member: dict[str, list[dict]] = {}
    for item in teaching_docs:
        teaching_by_member.setdefault(item["nick"], []).append(item)

    DATA.mkdir(parents=True, exist_ok=True)
    profile_sections = yaml.safe_load(
        (DATA / "profile_sections.yml").read_text(encoding="utf-8")
    ) or []

    people: list[dict] = []
    pages = 0
    for row in roster:
        nick = row["nick"]
        if not nick or nick in {"lab", "xyz"}:
            continue
        if not (row["name_en"] or row["name_zh"]):
            # Placeholder rows (identity TBD or GitHub aliases) stay in the private
            # roster but are not published.
            continue
        if row.get("hide"):
            # Roster marks this person as not shown on /team/ at all.
            continue
        section = section_for(row)
        papers = [short_paper(p) for p in pub_docs if nick in (p.get("lab_authors") or [])]
        tools = sorted(
            {
                key
                for paper in pub_docs
                if nick in (paper.get("lab_authors") or [])
                for key in (paper.get("tools") or [])
            } | tools_by_member.get(nick, set())
        )
        cv_url = cv_by_member.get(nick, row.get("cv_url", ""))
        teaching = teaching_by_member.get(nick, []) if row["degree"] == "Faculty" else []
        start, end = years(row)
        eligible_member = (
            section not in {"alumni", "collaborator", "visiting"}
            and row["status"] == "active"
            and (row["affiliation"].strip() in SCUT_AFFILIATION or section in {"pi", "faculty"})
        )
        section_material = {
            "cv": bool(cv_url),
            "publications": bool(papers),
            "teaching": bool(teaching),
            "tools": bool(tools),
        }
        has_page = (
            eligible_member
            and row.get("site") != "false"
            and any(section_material.values())
        )
        if row["nick"] == PI_NICK:
            # The PI's roster title wins ("Professor"); the section label is only
            # a fallback for when the roster carries no title at all.
            fallback_role = TITLE_BY_SECTION["pi"]
            role = role_text(row.get("title", ""), fallback_role)
            group = None
        elif section == "alumni":
            group = alumni_group(row["degree"], row.get("now", ""), row.get("title", ""), row.get("type", ""))
            role = group["role"]
            fallback_role = group["fallback"]
        elif section == "collaborator":
            # Collaborators already sit under a "Collaborators" heading, so the
            # section label adds nothing: show their own title instead, and leave
            # the role blank when the roster does not carry one.
            group = None
            fallback_role = ""
            role = role_text(row.get("title", ""), "")
        else:
            group = None
            fallback_role = (
                TITLE_BY_SECTION.get(section) or DEGREE_ROLE.get(row["degree"], row["degree"])
            )
            role = role_text(row.get("title", ""), fallback_role)
        display_name = row["name_en"] or row["name_zh"] or nick
        if display_name == row["name_en"]:
            display_name = first_last(display_name, row["name_zh"])
        if row.get("dr") and display_name and not display_name.startswith("Dr."):
            display_name = f"Dr. {display_name}"
        # An affiliation that only repeats the institution already in the "now"
        # line (or in the faculty title) would be shown twice on /team/.
        affil = row["affiliation"].strip()
        # Vague career notes ("就业") are not institutions, and "—"/"待定" are
        # blanks; neither should render as a stray separator on /team/.
        if (
            affil in SCUT_AFFILIATION
            or affil in PLACEHOLDER_AFFILIATIONS
            or affil in NON_INSTITUTIONAL_AFFILIATIONS
        ):
            affil = ""
        # A trailing "?" means the roster is unsure where someone went; publishing
        # "北大?" on a public page reads as an error, so keep it private.
        if affil.endswith(("?", "？")):
            affil = ""
        affiliation = affil
        now_text = place_text(row["now"]) if row.get("now") else ""
        if now_text and affiliation and same_place(affiliation, now_text):
            affiliation = ""
        # A faculty title that already names the institute says the same thing
        # the "now" line would ("Professor@惠州学院" + "now Prof@惠州学院").
        if now_text and role and role != fallback_role:
            place = now_text.rpartition("@")[2] or now_text
            if place and same_place(place, role):
                now_text = ""
        entry = {
            "nick": nick,
            "title": display_name,
            "name_en": display_name,
            "name_zh": row["name_zh"],
            "role": role,
            "degree": row["degree"],
            "section": section,
            "start_year": start,
            "end_year": end,
            "years": years_label(row, start, end),
            "status": row["status"] or "active",
            "affiliation": affiliation,
            "github": row["github"],
            "has_page": has_page,
            "site": has_page,
            "tools": tools,
            "papers": papers,
        }
        if section == "alumni":
            # /team/ renders the alumni as sub-sections in this order.
            entry["alumni_group"] = group["label"]
        if now_text:
            entry["now"] = now_text
        elif section == "alumni":
            # Without an explicit Now= marker, fall back to the affiliation cell,
            # skipping placeholders and entries the roster marks as uncertain.
            affil = row["affiliation"].strip()
            if (
                affil not in PLACEHOLDER_AFFILIATIONS
                and affil not in NON_INSTITUTIONAL_AFFILIATIONS
                and not affil.endswith(("?", "？"))
                and not (role and same_place(affil, role))
            ):
                entry["now"] = affil
                # The affiliation only fed the "now" line; showing it twice is noise.
                entry["affiliation"] = ""
        if cv_url:
            entry["cv_url"] = cv_url
        if has_page:
            explicit = (row.get("avatar") or "").strip()
            if explicit:
                entry["avatar"] = f"{AVATAR_ROOT}/{explicit}"
            else:
                entry["avatar"] = ensure_avatar(nick)
        people.append(entry)

        if has_page:
            front = {
                "layout": "profile",
                "permalink": f"/team/{nick}/",
                "redirect_from": [f"/{nick}/", f"/people/{nick}/"],
                **entry,
            }
            profile_dir = PROFILE_ROOT / nick
            profile_dir.mkdir(parents=True, exist_ok=True)
            page_path = profile_dir / "index.md"
            if page_path.exists() and PAGE_MARKER not in page_path.read_text(encoding="utf-8"):
                raise RuntimeError(f"refusing to overwrite hand-maintained profile: {page_path}")
            page_path.write_text(
                "---\n"
                + yaml.safe_dump(front, allow_unicode=True, sort_keys=False, width=100).strip()
                + f"\n---\n\n{PAGE_MARKER}\n",
                encoding="utf-8",
            )
            for section in profile_sections:
                section_key = section.get("key")
                section_path = (section.get("path") or "").strip("/")
                if not section_key or not section_path or not section_material.get(section_key):
                    continue
                section_page = profile_dir / section_path / "index.md"
                section_page.parent.mkdir(parents=True, exist_ok=True)
                section_front = {
                    "layout": "member-section",
                    "permalink": f"/team/{nick}/{section_path}/",
                    "redirect_from": f"/people/{nick}/{section_path}/",
                    "nick": nick,
                    "profile_section": section_key,
                    "title": f"{entry['name_en']} - {section.get('label', section_key)}",
                }
                if section_page.exists() and PAGE_MARKER not in section_page.read_text(encoding="utf-8"):
                    raise RuntimeError(f"refusing to overwrite hand-maintained profile section: {section_page}")
                section_page.write_text(
                    "---\n"
                    + yaml.safe_dump(section_front, allow_unicode=True, sort_keys=False, width=100).strip()
                    + f"\n---\n\n{PAGE_MARKER}\n",
                    encoding="utf-8",
                )
            for section_page in profile_dir.rglob("index.md"):
                text = section_page.read_text(encoding="utf-8")
                if PAGE_MARKER not in text or section_page == page_path:
                    continue
                try:
                    old_section = yaml.safe_load(text.split("---", 2)[1]) or {}
                except (IndexError, yaml.YAMLError):
                    continue
                section_key = old_section.get("profile_section")
                if section_key and not section_material.get(section_key, False):
                    section_page.unlink()
            pages += 1

    # Remove only the empty, generated collection pages from the old layout.
    for legacy_page in LEGACY_OUT_DIR.glob("*.md"):
        text = legacy_page.read_text(encoding="utf-8")
        if "layout: person" in text and text.rstrip().endswith("---"):
            legacy_page.unlink()
    if LEGACY_OUT_DIR.exists() and not any(LEGACY_OUT_DIR.iterdir()):
        LEGACY_OUT_DIR.rmdir()

    active_nicks = {p["nick"] for p in people if p["has_page"]}
    nonfaculty_nicks = {
        p["nick"] for p in people if p["has_page"] and p["degree"] != "Faculty"
    }

    # Remove only generated root-level profiles; redirect_from on the nested
    # profile preserves those public URLs through jekyll-redirect-from.
    for profile_page in OUT_DIR.glob("*/index.md"):
        text = profile_page.read_text(encoding="utf-8")
        if PAGE_MARKER not in text:
            continue
        try:
            old_profile = yaml.safe_load(text.split("---", 2)[1]) or {}
        except (IndexError, yaml.YAMLError):
            continue
        if old_profile.get("nick") not in active_nicks:
            continue
        profile_page.unlink()
        if not any(profile_page.parent.iterdir()):
            profile_page.parent.rmdir()

    for profile_page in PROFILE_ROOT.glob("*/index.md"):
        text = profile_page.read_text(encoding="utf-8")
        if PAGE_MARKER not in text:
            continue
        try:
            old_profile = yaml.safe_load(text.split("---", 2)[1]) or {}
        except (IndexError, yaml.YAMLError):
            continue
        if old_profile.get("nick") not in active_nicks:
            for generated_page in profile_page.parent.rglob("index.md"):
                if generated_page != profile_page and PAGE_MARKER in generated_page.read_text(encoding="utf-8"):
                    generated_page.unlink()
            for directory in sorted(
                (path for path in profile_page.parent.rglob("*") if path.is_dir()),
                key=lambda path: len(path.parts),
                reverse=True,
            ):
                if not any(directory.iterdir()):
                    directory.rmdir()
            write_team_redirect(profile_page, old_profile["nick"])

    for nick in previous_profiles - active_nicks:
        write_team_redirect(PROFILE_ROOT / nick / "index.md", nick)

    for nick in nonfaculty_nicks:
        profile_dir = PROFILE_ROOT / nick
        for section_page in profile_dir.rglob("index.md"):
            text = section_page.read_text(encoding="utf-8")
            if PAGE_MARKER not in text:
                continue
            try:
                section_front = yaml.safe_load(text.split("---", 2)[1]) or {}
            except (IndexError, yaml.YAMLError):
                continue
            if section_front.get("profile_section") == "teaching":
                section_page.unlink()
        for directory in sorted(
            (path for path in profile_dir.rglob("*") if path.is_dir()),
            key=lambda path: len(path.parts),
            reverse=True,
        ):
            if not any(directory.iterdir()):
                directory.rmdir()

    # Section order first; inside Alumni sort by sub-group then most recent exit.
    people.sort(
        key=lambda p: (
            SECTION_ORDER.index(p["section"]) if p["section"] in SECTION_ORDER else len(SECTION_ORDER),
            alumni_rank(p) if p["section"] == "alumni" else (p["start_year"] or "9999", p["nick"]),
        )
    )
    header = (
        "# Generated by _generators/gen_people.py - do not hand-edit.\n"
        "# Source: advisee/core/database/contact.md (public fields only).\n"
    )
    (DATA / "people.yml").write_text(
        header + yaml.safe_dump(people, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )
    print(f"people: {len(people)} roster entries, {pages} nested profiles, rest listed on /team/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
