#!/usr/bin/env python3
"""Build the people data (_data/people.yml) and per-member pages (/team/<nick>/index.md)
from the roster source of truth.

Source of truth: ~/work/advisee/core/database/contact.md (roster SoT).
Only public-safe fields are copied to the website: nick, English/Chinese name,
degree, entry/exit year, status, generic affiliation, GitHub handle, and links
to their tools/papers.  Contact details (email, mobile, WeChat/WeCom ids,
leader assignments, free-text notes) are deliberately NOT published.

Rule for individual pages: current group members get a page at /team/<nick>/
only when verified CV, publication, teaching, or tool material is available.
Alumni and external collaborators are listed on /team/ only.

Usage (WSL):  python3 _generators/gen_people.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from urllib.parse import urlsplit

import yaml

from gen_publications import REPO, load_roster

OUT_DIR = REPO
TEAM_DIR = "team"
PROFILE_ROOT = REPO / TEAM_DIR
LEGACY_OUT_DIR = REPO / "_people"
DATA = REPO / "_data"
PUBLICATIONS = DATA / "publications.yml"
TOOLS = DATA / "tools.yml"
MEMBER_PROFILES = DATA / "member_profiles.yml"
PAGE_MARKER = "<!-- Generated by _generators/gen_people.py; edit the roster source instead. -->"

# Faculty rows that are collaborators or former visitors, not current members.
EXTERNAL_FACULTY = {"adm", "fyl", "jdy", "lxm", "lyz", "lqj"}

DEGREE_ROLE = {
    "Faculty": "Faculty",
    "PhD": "PhD student",
    "Master": "Master's student",
    "Under": "Undergraduate researcher",
}

TITLE_BY_SECTION = {
    "pi": "Principal Investigator",
    "faculty": "Faculty",
    "phd": "PhD student",
    "master": "Master's student",
    "under": "Undergraduate researcher",
}

SCUT_AFFILIATION = {"", "n.a.", "在校", "华南理工大学"}


def section_for(row: dict) -> str:
    if row["nick"] == "lcx":
        return "pi"
    if row["status"] == "alumni" or row["nick"] in EXTERNAL_FACULTY:
        return "alumni"
    return {
        "Faculty": "faculty",
        "PhD": "phd",
        "Master": "master",
        "Under": "under",
    }.get(row["degree"], "under")


def years(row: dict) -> tuple[str, str]:
    """'2023i' -> ('2023', '');  '2022/2025o' -> ('2022', '2025')."""
    parts = (row["year"] or "").split("/")
    start = re.sub(r"\D", "", parts[0]) if parts and parts[0] else ""
    end = re.sub(r"\D", "", parts[1]) if len(parts) > 1 else ""
    return start, end


def short_paper(entry: dict) -> dict:
    return {
        "slug": entry["slug"],
        "title": entry["title"],
        "venue": entry.get("venue_short") or entry["venue"],
        "year": entry["year"],
        "url": entry["url"],
        "status": entry.get("status", ""),
    }


def tracked_profile_nicks() -> set[str]:
    result = subprocess.run(
        ["git", "-C", str(REPO), "ls-tree", "-r", "--name-only", "HEAD", "--", TEAM_DIR],
        check=True,
        capture_output=True,
        text=True,
    )
    return {
        parts[1]
        for path in result.stdout.splitlines()
        if len(parts := path.split("/")) == 3
        and parts[0] == TEAM_DIR
        and parts[2] == "index.md"
    }


def cv_links_by_member(
    profiles: list[dict], roster_nicks: set[str]
) -> dict[str, str]:
    """Return verified-format public PDF links keyed by roster nick."""
    cv_by_member: dict[str, str] = {}
    for item in profiles:
        nick = item.get("nick")
        cv_url = item.get("cv_url")
        if not nick or not cv_url:
            continue
        if nick not in roster_nicks:
            raise ValueError(f"unknown member in {MEMBER_PROFILES}: {nick}")
        parsed_cv = urlsplit(cv_url)
        if parsed_cv.scheme != "https" or not parsed_cv.path.lower().endswith(".pdf"):
            raise ValueError(f"CV URL must be an HTTPS PDF link for {nick}: {cv_url}")
        repository_url = item.get("cv_repository_url", "")
        if repository_url:
            parsed_repository = urlsplit(repository_url)
            repository_name = parsed_repository.path.rstrip("/").split("/")[-1]
            if (
                parsed_repository.scheme != "https"
                or parsed_repository.netloc.lower() != "github.com"
                or repository_name.casefold() != nick.casefold()
            ):
                raise ValueError(
                    f"CV repository must be a public GitHub repository named for "
                    f"{nick}: {repository_url}"
                )
        cv_by_member[nick] = cv_url
    return cv_by_member


def write_team_redirect(path, nick: str) -> None:
    front = {
        "layout": "default",
        "permalink": f"/team/{nick}/",
        "redirect_to": "/team/",
        "redirect_from": [f"/{nick}/", f"/people/{nick}/"],
        "nick": nick,
        "has_page": False,
        "title": "Team",
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and PAGE_MARKER not in path.read_text(encoding="utf-8"):
        raise RuntimeError(f"refusing to overwrite hand-maintained profile: {path}")
    path.write_text(
        "---\n"
        + yaml.safe_dump(front, allow_unicode=True, sort_keys=False, width=100).strip()
        + f"\n---\n\n{PAGE_MARKER}\n",
        encoding="utf-8",
    )


def main() -> int:
    previous_profiles = tracked_profile_nicks()
    roster = load_roster()
    pub_docs: list[dict] = []
    if PUBLICATIONS.exists():
        pub_docs = yaml.safe_load(PUBLICATIONS.read_text(encoding="utf-8")) or []
    tool_docs = yaml.safe_load(TOOLS.read_text(encoding="utf-8")) or []
    teaching_docs = yaml.safe_load(
        (DATA / "member_teaching.yml").read_text(encoding="utf-8")
    ) or []
    member_profile_docs = yaml.safe_load(
        MEMBER_PROFILES.read_text(encoding="utf-8")
    ) or []
    cv_by_member = cv_links_by_member(
        member_profile_docs, {row["nick"] for row in roster}
    )
    tools_by_member: dict[str, set[str]] = {}
    for tool in tool_docs:
        for nick in tool.get("maintainers") or []:
            tools_by_member.setdefault(nick, set()).add(tool["key"])
    teaching_by_member: dict[str, list[dict]] = {}
    for item in teaching_docs:
        teaching_by_member.setdefault(item["nick"], []).append(item)

    DATA.mkdir(parents=True, exist_ok=True)
    profile_sections = yaml.safe_load(
        (DATA / "profile_sections.yml").read_text(encoding="utf-8")
    ) or []

    people: list[dict] = []
    pages = 0
    for row in roster:
        nick = row["nick"]
        if not nick or nick in {"lab", "xyz"}:
            continue
        section = section_for(row)
        papers = [short_paper(p) for p in pub_docs if nick in (p.get("lab_authors") or [])]
        tools = sorted(
            {
                key
                for paper in pub_docs
                if nick in (paper.get("lab_authors") or [])
                for key in (paper.get("tools") or [])
            } | tools_by_member.get(nick, set())
        )
        cv_url = cv_by_member.get(nick, row.get("cv_url", ""))
        teaching = teaching_by_member.get(nick, []) if row["degree"] == "Faculty" else []
        start, end = years(row)
        eligible_member = (
            section != "alumni"
            and row["status"] == "active"
            and (row["affiliation"].strip() in SCUT_AFFILIATION or section in {"pi", "faculty"})
        )
        section_material = {
            "cv": bool(cv_url),
            "publications": bool(papers),
            "teaching": bool(teaching),
            "tools": bool(tools),
        }
        has_page = eligible_member and any(section_material.values())
        entry = {
            "nick": nick,
            "title": row["name_en"] or row["name_zh"] or nick,
            "name_en": row["name_en"],
            "name_zh": row["name_zh"],
            "role": TITLE_BY_SECTION.get(section, DEGREE_ROLE.get(row["degree"], row["degree"])),
            "degree": row["degree"],
            "section": section,
            "start_year": start,
            "end_year": end,
            "status": row["status"] or "active",
            "affiliation": "" if row["affiliation"].strip() in SCUT_AFFILIATION else row["affiliation"],
            "github": row["github"],
            "has_page": has_page,
            "tools": tools,
            "papers": papers,
        }
        if cv_url:
            entry["cv_url"] = cv_url
        people.append(entry)

        if has_page:
            front = {
                "layout": "profile",
                "permalink": f"/team/{nick}/",
                "redirect_from": [f"/{nick}/", f"/people/{nick}/"],
                **entry,
            }
            profile_dir = PROFILE_ROOT / nick
            profile_dir.mkdir(parents=True, exist_ok=True)
            page_path = profile_dir / "index.md"
            if page_path.exists() and PAGE_MARKER not in page_path.read_text(encoding="utf-8"):
                raise RuntimeError(f"refusing to overwrite hand-maintained profile: {page_path}")
            page_path.write_text(
                "---\n"
                + yaml.safe_dump(front, allow_unicode=True, sort_keys=False, width=100).strip()
                + f"\n---\n\n{PAGE_MARKER}\n",
                encoding="utf-8",
            )
            for section in profile_sections:
                section_key = section.get("key")
                section_path = (section.get("path") or "").strip("/")
                if not section_key or not section_path or not section_material.get(section_key):
                    continue
                section_page = profile_dir / section_path / "index.md"
                section_page.parent.mkdir(parents=True, exist_ok=True)
                section_front = {
                    "layout": "member-section",
                    "permalink": f"/team/{nick}/{section_path}/",
                    "redirect_from": f"/people/{nick}/{section_path}/",
                    "nick": nick,
                    "profile_section": section_key,
                    "title": f"{entry['name_en']} - {section.get('label', section_key)}",
                }
                if section_page.exists() and PAGE_MARKER not in section_page.read_text(encoding="utf-8"):
                    raise RuntimeError(f"refusing to overwrite hand-maintained profile section: {section_page}")
                section_page.write_text(
                    "---\n"
                    + yaml.safe_dump(section_front, allow_unicode=True, sort_keys=False, width=100).strip()
                    + f"\n---\n\n{PAGE_MARKER}\n",
                    encoding="utf-8",
                )
            for section_page in profile_dir.rglob("index.md"):
                text = section_page.read_text(encoding="utf-8")
                if PAGE_MARKER not in text or section_page == page_path:
                    continue
                try:
                    old_section = yaml.safe_load(text.split("---", 2)[1]) or {}
                except (IndexError, yaml.YAMLError):
                    continue
                section_key = old_section.get("profile_section")
                if section_key and not section_material.get(section_key, False):
                    section_page.unlink()
            pages += 1

    # Remove only the empty, generated collection pages from the old layout.
    for legacy_page in LEGACY_OUT_DIR.glob("*.md"):
        text = legacy_page.read_text(encoding="utf-8")
        if "layout: person" in text and text.rstrip().endswith("---"):
            legacy_page.unlink()
    if LEGACY_OUT_DIR.exists() and not any(LEGACY_OUT_DIR.iterdir()):
        LEGACY_OUT_DIR.rmdir()

    active_nicks = {p["nick"] for p in people if p["has_page"]}
    nonfaculty_nicks = {
        p["nick"] for p in people if p["has_page"] and p["degree"] != "Faculty"
    }

    # Remove only generated root-level profiles; redirect_from on the nested
    # profile preserves those public URLs through jekyll-redirect-from.
    for profile_page in OUT_DIR.glob("*/index.md"):
        text = profile_page.read_text(encoding="utf-8")
        if PAGE_MARKER not in text:
            continue
        try:
            old_profile = yaml.safe_load(text.split("---", 2)[1]) or {}
        except (IndexError, yaml.YAMLError):
            continue
        if old_profile.get("nick") not in active_nicks:
            continue
        profile_page.unlink()
        if not any(profile_page.parent.iterdir()):
            profile_page.parent.rmdir()

    for profile_page in PROFILE_ROOT.glob("*/index.md"):
        text = profile_page.read_text(encoding="utf-8")
        if PAGE_MARKER not in text:
            continue
        try:
            old_profile = yaml.safe_load(text.split("---", 2)[1]) or {}
        except (IndexError, yaml.YAMLError):
            continue
        if old_profile.get("nick") not in active_nicks:
            for generated_page in profile_page.parent.rglob("index.md"):
                if generated_page != profile_page and PAGE_MARKER in generated_page.read_text(encoding="utf-8"):
                    generated_page.unlink()
            for directory in sorted(
                (path for path in profile_page.parent.rglob("*") if path.is_dir()),
                key=lambda path: len(path.parts),
                reverse=True,
            ):
                if not any(directory.iterdir()):
                    directory.rmdir()
            write_team_redirect(profile_page, old_profile["nick"])

    for nick in previous_profiles - active_nicks:
        write_team_redirect(PROFILE_ROOT / nick / "index.md", nick)

    for nick in nonfaculty_nicks:
        profile_dir = PROFILE_ROOT / nick
        for section_page in profile_dir.rglob("index.md"):
            text = section_page.read_text(encoding="utf-8")
            if PAGE_MARKER not in text:
                continue
            try:
                section_front = yaml.safe_load(text.split("---", 2)[1]) or {}
            except (IndexError, yaml.YAMLError):
                continue
            if section_front.get("profile_section") == "teaching":
                section_page.unlink()
        for directory in sorted(
            (path for path in profile_dir.rglob("*") if path.is_dir()),
            key=lambda path: len(path.parts),
            reverse=True,
        ):
            if not any(directory.iterdir()):
                directory.rmdir()

    people.sort(key=lambda p: (p["section"], p["start_year"] or "9999", p["nick"]))
    header = (
        "# Generated by _generators/gen_people.py - do not hand-edit.\n"
        "# Source: advisee/core/database/contact.md (public fields only).\n"
    )
    (DATA / "people.yml").write_text(
        header + yaml.safe_dump(people, allow_unicode=True, sort_keys=False, width=100),
        encoding="utf-8",
    )
    print(f"people: {len(people)} roster entries, {pages} nested profiles, rest listed on /team/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
